### ISSUE TITLE
@{version} doesn't get resolved in <tagReleaseMessage>

### ISSUE THREAD

**Issue by Wavemaster111188** [aleksandr-m/gitflow-maven-plugin#113]
### Problem
If you use @{version} in a tag it simply isn't applied (instead it shows the plain text "@{version}").

### Reason
This is because the properties map is not taken into account for tagging.

The following code is executed in `gitCommit` but not in `gitTag`: 

```java
       if (map != null) {
            for (Entry<String, String> entr : map.entrySet()) {
                message = StringUtils.replace(message, "@{" + entr.getKey()
                        + "}", entr.getValue());
            }
        }
```
### Solution
The solution would be to add a `gitTag(final String tagName, final String message, boolean gpgSignTag , Map<String, String> map)` method and use the above code in the method.

Then in all tagging Mojos, the new method should be used.

I see no downside in this behaviour.
  
   
_(this is my very first public issue ever so please help me if I'm done something wrong)_

**Comment by aleksandr-m** [comment]
@Wavemaster111188  You can use maven `${project.version}` in tag messages. It should work because when tagging is done the version in pom is not changed yet. Try it out.

**Comment by Wavemaster111188** [comment]
@aleksandr-m  
The `${project.version}` resolves to the SNAPSHOT version of the current release (if I tag `1.2.3.4`, it resolves to `1.2.3.4-SNAPSHOT`)

For annotating tags, I need the released version, not the SNAPSHOT, therefore the issue.

**Comment by aleksandr-m** [comment]
@Wavemaster111188 Yes. I didn't change the branch so for me it was correct version. Done.

**Comment by Wavemaster111188** [comment]
Awesome!  
Thanks a lot.

**Comment by testphreak** [comment]
@aleksandr-m thank you for releasing the new version! Can you share more about this `@{version}` property and how it can be used with this plugin? I looked for examples but didn't come across any except that it can be used as custom property in commit messages.

Wondering if I can use `@{version}` inside `postReleaseGoals` to set the release version instead of the snapshot version, something like `-DcustomVersion=@{version}`. If I use `${project.version}` it uses the snapshot version.
