### ISSUE TITLE
settings parameter is not documented

### ISSUE THREAD

**Issue by DVanderstoken** [aleksandr-m/gitflow-maven-plugin#15]
Is this parameter intended to specify a settings file?

**Comment by aleksandr-m** [comment]
You mean this [`settings`](https://github.com/aleksandr-m/gitflow-maven-plugin/blob/master/src/main/java/com/amashchenko/maven/plugin/gitflow/AbstractGitFlowMojo.java#L130)? It is maven settings, and not a settable property.

**Comment by DVanderstoken** [comment]
Yes. This one. Is-it possible to specify maven settings file to be used during release ?

**Comment by aleksandr-m** [comment]
Sure see [maven command line how to point to a specific settings.xml for a single command?](http://stackoverflow.com/q/25277866/1700321).

**Comment by DVanderstoken** [comment]
Yes, i know how to launch maven command line with specific settings file. But in your mojo, you re-launch maven command without allowing to specify a specific settings file. So, the default settings file is used and it isn't what i want...

**Comment by aleksandr-m** [comment]
What do you want to achieve then?

**Comment by aleksandr-m** [comment]
@DVanderstoken ping

**Comment by srsp** [comment]
When I start

`mvn gitflow:release-start  -s ../jenkins-settings/mvn/settings.xml`

then artifacts from a certain repository defined in the above `settings.xml` cannot be downloaded, because the repository answers with `unauthorized`. The settings file contains the credentials for this repository. So I think one of the mvn subprocesses does not honor the settings given to the parent mvn process.

I think this is what @DVanderstoken meant and currently I have the same problem. Is there a way to hand down the settings file to the child mvn process?

**Comment by aleksandr-m** [comment]
@srsp Could be. Any thoughts on how it can be reproduced w/o messing with custom repository?

**Comment by srsp** [comment]
My setup is a bit complicated with a commercial artifact only available in repository that needs authentication. I tried to setup a minimal configuration to show the problem, but was not yet successful. 

I found a way to work around this by changing our infrastructure. I will still try to reproduce it in a simple setup, but since the pressure is gone it might take a while.

**Comment by aleksandr-m** [comment]
@srsp I think new parameter can be introduced that will take arguments as a string and put them to underlying maven commands.

Thanks for reporting.

**Comment by aleksandr-m** [comment]
@srsp The [`argLine`](https://github.com/aleksandr-m/gitflow-maven-plugin#maven-arguments) parameter was added in `1.8.0`.

**Comment by srsp** [comment]
@aleksandr-m Thank you! I will try it out.

**Comment by srsp** [comment]
I know this is old and closed, but here's my feedback anyway: We use the `argLine` parameter and it works like a charm!

**Comment by aleksandr-m** [comment]
@srsp Feedback is always welcome! :)
