### ISSUE TITLE
Add "featureName" option in feature-start goal

### ISSUE THREAD

**Issue by thordickinson** [aleksandr-m/gitflow-maven-plugin#71]
Please add an option to start and finish a feature in non-interactive mode by using a parameter.

Thanks

**Comment by hfatela** [comment]
I would like to support this request. 

We need to create jenkins jobs that will use this plugin and keep its inner works hidden to the users, the idea is to just ask for some parameters and run from there. 
In the last couple of years we used JGitFlow to achive this, but since that project is dead we want to change this one but the fact we can't avoid interactive mode in the hotfix and feature, by passing a parameter with the branch name we want to create or finish, is preventing us from using this plugin with jenkins.

**Comment by aleksandr-m** [comment]
@hfatela Sure. It will take some time though. The next release will be all about maven goals - #54 :)

**Comment by aleksandr-m** [comment]
@thordickinson @hfatela `1.9.0` is released.
