### ISSUE TITLE
deployment after release finish

### ISSUE THREAD

**Issue by flashpixx** [aleksandr-m/gitflow-maven-plugin#93]
Hello,

a nice optional feature is, that the deployment call on Maven can be run immediatly after ```mvn gitflow:release-finish```, but on this the version must be contain ```-SNAPSHOT``` and the deployment is done by ```mvn clean release:clean release:prepare release:perform``` with the Maven Release Plugin.
This connection between the normal release plugin can be very helpful

**Comment by aleksandr-m** [comment]
@flashpixx Why do you need the Maven Release Plugin? Deployment? You can add `deploy` goal in `postReleaseGoals` parameter.

**Comment by aleksandr-m** [comment]
@magullo Is there any issue with using `postReleaseGoals` parameter?

**Comment by Og1001** [comment]
I'll try to describe use case behind release-finish that we expect.
1. release-finish runs either 'clean verify' if tychoBuild=true or 'clean test' otherwise. It's ok.
2. Then we usually deploy artifacts into the nexus repo immediately after release-finish and drop branch. But if you use `postReleaseGoals` maven will go though all phases, i.e. it will run tests again, etc. 
If you use argLine with -DskipTests=true it will affect ability of gitflow plugin to run tests (see point 1) because plugin uses one method for this `executeMvnCommand` and it's turn it uses `executeCommand(cmdMvn, true, argLine, args)`. argLine is class attribute that contains our `-DskipTests=true`. Dead end.
As workaround we can use skipTestProject=true and run tests with deploy. Fortunately plugin will push everything only after successful deployment to repository.
It would be better to run tests with release-finish and then deploy without tests because it makes sense for release process in my project. 
I would suggest to introduce new parameter deployProject (like installProject) and make point 1 independent of argLine parameter. argLine should affect only pre and post goals in my understanding.

**Comment by aleksandr-m** [comment]
@Og1001 You can skip testing and installing with parameters and you can put parameters to the `postReleaseGoals` directly without using `argLine`.
